# For more information: https://laravel.com/docs/sail
version: '3'
services:

    # INFLUX DB
    influxdb2:
        image: influxdb:latest
        network_mode: "bridge"
        container_name: influxdb2
        ports:
          - "8086:8086"
        volumes:
          - type: bind
            source: /home/smec/volume1/docker/influxdb2/data
            target: /var/lib/influxdb2
          - type: bind
            source: /home/smec/volume1/docker/influxdb2/config
            target: /etc/influxdb2
        environment:
          - DOCKER_INFLUXDB_INIT_MODE=setup
          - DOCKER_INFLUXDB_INIT_USERNAME=hips
          - DOCKER_INFLUXDB_INIT_PASSWORD=Letmein100
          - DOCKER_INFLUXDB_INIT_ORG=HIPS
          - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
          - DOCKER_INFLUXDB_INIT_RETENTION=1w
          - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=D6gQJkUO2Wbie5Mv4TChTRITwMwwJgJmWOF89VfYxrEjYPkbOXDsaDS9KqEBMNJEjW1sJxV66AUr1PO0nN0_WQ
        restart: always

    # GRAFANA
    grafana:
        image: grafana/grafana
        restart: always
        depends_on:
          - influxdb2
        build:
          context: ""
          dockerfile: DockerfileGrafana
        container_name: grafana
        links:
          - influxdb2
        ports:
          - "3000:3000"
        volumes:
          - grafana-data:/var/lib/grafana
        networks:
          - grafnet

    # TELEGRAF
    telegraf:
        image: telegraf:latest
        network_mode: "bridge"
        pid: "host"
        container_name: telegraf
        volumes:
          - /home/smec/volume1/docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /sys:/host/sys:ro
          - /proc:/host/proc:ro
          - /etc:/host/etc:ro
        environment:
          - HOST_PROC=/host/proc
          - HOST_SYS=/host/sys
          - HOST_ETC=/host/etc
        restart: always

networks:
    grafnet:
        external: true
    monitoring:

# Explicitly define the persistent volume for your data storage
volumes:
  grafana-data:
      name: grafana-data
      external: false
  influxdb-volume:
      external: true