# For more information: https://laravel.com/docs/sail
version: '3'
services:

    #PHP Service
    app:
      build:
        context: ./
        dockerfile: Dockerfile
      image: wc_backend
      container_name: app_wc
      restart: unless-stopped
      tty: true
      environment:
        SERVICE_NAME: app_wc_tms
        SERVICE_TAGS: dev
      working_dir: /var/www/html/
      volumes:
        - ./:/var/www/html/
        - .env:/var/www/html/.env
      ports:
        - "9002:80"
      networks:
        - app-network

networks:
    app-network:
